### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by BDE666** [grammarly/gector#200]
C:\Users\89314\.conda\envs\gector-master\lib\site-packages\sklearn\utils\validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /roberta-base/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\urllib3\connectionpool.py", line 713, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\urllib3\connectionpool.py", line 1015, in _prepare_proxy
    conn.connect()
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\urllib3\connection.py", line 510, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\urllib3\util\ssl_.py", line 462, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\89314\.conda\envs\gector-master\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\89314\.conda\envs\gector-master\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\89314\.conda\envs\gector-master\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\requests\adapters.py", line 497, in send
    chunked=chunked,
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\urllib3\connectionpool.py", line 803, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /roberta-base/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\transformers\configuration_utils.py", line 554, in get_config_dict   
    user_agent=user_agent,
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\transformers\file_utils.py", line 1410, in cached_path
    local_files_only=local_files_only,
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\transformers\file_utils.py", line 1573, in get_from_cache
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=etag_timeout)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /roberta-base/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 311, in <module>
    main(args)
  File "train.py", line 104, in main
    special_tokens_fix=args.special_tokens_fix)
  File "train.py", line 60, in get_data_reader
    special_tokens_fix=special_tokens_fix
  File "train.py", line 32, in get_token_indexers
    special_tokens_fix=special_tokens_fix
  File "C:\Users\89314\Desktop\gector-master\gector-master\gector\tokenizer_indexer.py", line 143, in __init__
    model_name, do_lower_case=do_lowercase, do_basic_tokenize=False, use_fast=True)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 463, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\transformers\models\auto\configuration_auto.py", line 527, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\89314\.conda\envs\gector-master\lib\site-packages\transformers\configuration_utils.py", line 570, in get_config_dict   
    raise EnvironmentError(msg)
OSError: Can't load config for 'roberta-base'. Make sure that:

- 'roberta-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'roberta-base' is the correct path to a directory containing a config.json file

训练时选用roberta-base模型后报错，是什么原因呢？

**Comment by jaysontree** [comment]
你这个单纯连不上huggingface. 环境变量配下镜像地址
