### ISSUE TITLE
torch.cuda.FloatTensor in seq2labels_model.py

### ISSUE THREAD

**Issue by zl930216** [grammarly/gector#59]
line 145, if not cuda.is_available(), torch.FloatTensor should be correct instead.

**Comment by skurzhanskyi** [comment]
Good point. We usually ran it on GPU, so we missed this. Thanks
We'll fix later

**Comment by amiyamandal-dev** [comment]
```
Traceback (most recent call last):

  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f17e1cb5e18>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f17e1cb5bf8>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
    │    │        │    └ (<weakref at 0x7f1729bb0408; to 'ThreadPoolExecutor' at 0x7f17e175bcc0>, <queue.Queue object at 0x7f1725817358>)
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
    │    └ <function _worker at 0x7f17e17a2950>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/concurrent/futures/thread.py", line 69, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f17e17a2a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f1729be48d0>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f1729be48d0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f1729bb0318>, <grpc._server._RPCState object at 0x7f1729be47f0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f1729be48d0>
             │    └ <function _unary_response_in_pool at 0x7f1729bd09d8>
             └ <concurrent.futures.thread._WorkItem object at 0x7f1729be48d0>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/grpc/_server.py", line 553, in _unary_response_in_pool
    argument, request_deserializer)
    │         └ <built-in method FromString of GeneratedProtocolMessageType object at 0x55ddfb3bec78>
    └ input_string: "I was a bad day"
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f1729be4ac8>
                           │        └ input_string: "I was a bad day"
                           │          
                           └ <bound method GrammerModel.GetResult of <__main__.GrammerModel object at 0x7f1725817588>>

> File "server_grammer_model.py", line 64, in GetResult
    rez = string_grammer_update(val_string)
          │                     └ 'I was a bad day'
          └ <function string_grammer_update at 0x7f172581fd90>

  File "server_grammer_model.py", line 53, in string_grammer_update
    preds, cnt = model.handle_batch(batch)
                 │     │            └ [['I', 'was', 'a', 'bad', 'day']]
                 │     └ <function GecBERTModel.handle_batch at 0x7f173f073730>
                 └ <gector.gec_model.GecBERTModel object at 0x7f17e1d85fd0>

  File "/home/amiya/workspace/abcd/gector/gector/gec_model.py", line 309, in handle_batch
    probabilities, idxs, error_probs = self.predict(sequences)
                                       │    │       └ [<allennlp.data.dataset.Batch object at 0x7f1729be4fd0>]
                                       │    └ <function GecBERTModel.predict at 0x7f173f0732f0>
                                       └ <gector.gec_model.GecBERTModel object at 0x7f17e1d85fd0>

  File "/home/amiya/workspace/abcd/gector/gector/gec_model.py", line 140, in predict
    prediction = model.forward(**batch)
                 │     │         └ {'tokens': {'bert': tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
                 │     │                      948,   191,  41...
                 │     └ <function Seq2Labels.forward at 0x7f1741dd5510>
                 └ Seq2Labels(
                     (text_field_embedder): BasicTextFieldEmbedder(
                       (token_embedder_bert): PretrainedBertEmbedder(
                         (bert_m...

  File "/home/amiya/workspace/abcd/gector/gector/seq2labels_model.py", line 130, in forward
    encoded_text = self.text_field_embedder(tokens)
                   │                        └ {'bert': tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
                   │                                     948,   191,  4145,    83, ...
                   └ Seq2Labels(
                       (text_field_embedder): BasicTextFieldEmbedder(
                         (token_embedder_bert): PretrainedBertEmbedder(
                           (bert_m...

  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ ({'bert': tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
             │    │                     948,   191,  4145,    83,...
             │    └ <function BasicTextFieldEmbedder.forward at 0x7f174262b620>
             └ BasicTextFieldEmbedder(
                 (token_embedder_bert): PretrainedBertEmbedder(
                   (bert_model): XLNetModel(
                     (word_embedding)...
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 110, in forward
    token_vectors = embedder(*tensors)
                    │         └ [tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
                    │                      948,   191,  4145,    83,  8186,  ...
                    └ PretrainedBertEmbedder(
                        (bert_model): XLNetModel(
                          (word_embedding): Embedding(32000, 768)
                          (layer): ModuleList(
                          ...
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
             │    │                     948,   191,  4145,    83,  8186,  ...
             │    └ <function BertEmbedder.forward at 0x7f1742028bf8>
             └ PretrainedBertEmbedder(
                 (bert_model): XLNetModel(
                   (word_embedding): Embedding(32000, 768)
                   (layer): ModuleList(
                   ...

  File "/home/amiya/workspace/abcd/gector/gector/bert_token_embedder.py", line 147, in forward
    attention_mask=util.combine_initial_dims(input_mask),
                   │    │                    └ tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0')
                   │    └ <function combine_initial_dims at 0x7f174699bbf8>
                   └ <module 'allennlp.nn.util' from '/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/allennlp/nn/util.py'>

  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
             │    │        │        └ {'input_ids': tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
             │    │        │                     948,   191,  4145,   ...
             │    │        └ ()
             │    └ <function XLNetModel.forward at 0x7f1741ff9400>
             └ XLNetModel(
                 (word_embedding): Embedding(32000, 768)
                 (layer): ModuleList(
                   (0): XLNetLayer(
                     (rel_attn): XLNetRela...
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/transformers/modeling_xlnet.py", line 798, in forward
    word_emb_k = self.word_embedding(input_ids)
                 │                   └ tensor([[ 4145],
                 │                             [ 7416],
                 │                             [   83],
                 │                             [ 3158],
                 │                             [ 6490],
                 │                             [24531],
                 │                             [  658],
                 │                           ...
                 └ XLNetModel(
                     (word_embedding): Embedding(32000, 768)
                     (layer): ModuleList(
                       (0): XLNetLayer(
                         (rel_attn): XLNetRela...
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[ 4145],
             │    │                  [ 7416],
             │    │                  [   83],
             │    │                  [ 3158],
             │    │                  [ 6490],
             │    │                  [24531],
             │    │                  [  658],
             │    │               ...
             │    └ <function Embedding.forward at 0x7f17d4b24bf8>
             └ Embedding(32000, 768)
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
    │    │          │    │                   │    └ False
    │    │          │    │                   └ Embedding(32000, 768)
    │    │          │    └ False
    │    │          └ Embedding(32000, 768)
    │    └ 2.0
    └ Embedding(32000, 768)
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           │     │         │       │      │            │                   └ False
           │     │         │       │      │            └ False
           │     │         │       │      └ -1
           │     │         │       └ tensor([[ 4145],
           │     │         │                 [ 7416],
           │     │         │                 [   83],
           │     │         │                 [ 3158],
           │     │         │                 [ 6490],
           │     │         │                 [24531],
           │     │         │                 [  658],
           │     │         │               ...
           │     │         └ Parameter containing:
           │     │           tensor([[-0.0049,  0.0655, -0.0151,  ..., -0.0458, -0.0061,  0.0346],
           │     │                   [ 0.0395,  0.0205,  0.010...
           │     └ <built-in method embedding of type object at 0x7f17dc678220>
           └ <module 'torch' from '/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/__init__.py'>

RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_index_select
2020-09-24 13:07:29.935 | INFO     | __main__:GetResult:65 - sending value ->None
2020-09-24 13:07:31.866 | INFO     | __main__:GetResult:63 - request has been recieved ->I was a bad day
2020-09-24 13:07:31.875 | ERROR    | __main__:GetResult:64 - An error has been caught in function 'GetResult', process 'MainProcess' (396420), thread 'ThreadPoolExecutor-0_0' (139737272723200):
Traceback (most recent call last):

  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f17e1cb5e18>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f17e1cb5bf8>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
    │    │        │    └ (<weakref at 0x7f1729bb0408; to 'ThreadPoolExecutor' at 0x7f17e175bcc0>, <queue.Queue object at 0x7f1725817358>)
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
    │    └ <function _worker at 0x7f17e17a2950>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 139737272723200)>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/concurrent/futures/thread.py", line 69, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f17e17a2a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f1727ef0f98>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f1727ef0f98>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f1729bb04f8>, <grpc._server._RPCState object at 0x7f1727ef0358>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f1727ef0f98>
             │    └ <function _unary_response_in_pool at 0x7f1729bd09d8>
             └ <concurrent.futures.thread._WorkItem object at 0x7f1727ef0f98>
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/grpc/_server.py", line 553, in _unary_response_in_pool
    argument, request_deserializer)
    │         └ <built-in method FromString of GeneratedProtocolMessageType object at 0x55ddfb3bec78>
    └ input_string: "I was a bad day"
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f1729be4b38>
                           │        └ input_string: "I was a bad day"
                           │          
                           └ <bound method GrammerModel.GetResult of <__main__.GrammerModel object at 0x7f1725817588>>

> File "server_grammer_model.py", line 64, in GetResult
    rez = string_grammer_update(val_string)
          │                     └ 'I was a bad day'
          └ <function string_grammer_update at 0x7f172581fd90>

  File "server_grammer_model.py", line 53, in string_grammer_update
    preds, cnt = model.handle_batch(batch)
                 │     │            └ [['I', 'was', 'a', 'bad', 'day']]
                 │     └ <function GecBERTModel.handle_batch at 0x7f173f073730>
                 └ <gector.gec_model.GecBERTModel object at 0x7f17e1d85fd0>

  File "/home/amiya/workspace/abcd/gector/gector/gec_model.py", line 309, in handle_batch
    probabilities, idxs, error_probs = self.predict(sequences)
                                       │    │       └ [<allennlp.data.dataset.Batch object at 0x7f1729be4cc0>]
                                       │    └ <function GecBERTModel.predict at 0x7f173f0732f0>
                                       └ <gector.gec_model.GecBERTModel object at 0x7f17e1d85fd0>

  File "/home/amiya/workspace/abcd/gector/gector/gec_model.py", line 140, in predict
    prediction = model.forward(**batch)
                 │     │         └ {'tokens': {'bert': tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
                 │     │                      948,   191,  41...
                 │     └ <function Seq2Labels.forward at 0x7f1741dd5510>
                 └ Seq2Labels(
                     (text_field_embedder): BasicTextFieldEmbedder(
                       (token_embedder_bert): PretrainedBertEmbedder(
                         (bert_m...

  File "/home/amiya/workspace/abcd/gector/gector/seq2labels_model.py", line 130, in forward
    encoded_text = self.text_field_embedder(tokens)
                   │                        └ {'bert': tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
                   │                                     948,   191,  4145,    83, ...
                   └ Seq2Labels(
                       (text_field_embedder): BasicTextFieldEmbedder(
                         (token_embedder_bert): PretrainedBertEmbedder(
                           (bert_m...

  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ ({'bert': tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
             │    │                     948,   191,  4145,    83,...
             │    └ <function BasicTextFieldEmbedder.forward at 0x7f174262b620>
             └ BasicTextFieldEmbedder(
                 (token_embedder_bert): PretrainedBertEmbedder(
                   (bert_model): XLNetModel(
                     (word_embedding)...
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 110, in forward
    token_vectors = embedder(*tensors)
                    │         └ [tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
                    │                      948,   191,  4145,    83,  8186,  ...
                    └ PretrainedBertEmbedder(
                        (bert_model): XLNetModel(
                          (word_embedding): Embedding(32000, 768)
                          (layer): ModuleList(
                          ...
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
             │    │                     948,   191,  4145,    83,  8186,  ...
             │    └ <function BertEmbedder.forward at 0x7f1742028bf8>
             └ PretrainedBertEmbedder(
                 (bert_model): XLNetModel(
                   (word_embedding): Embedding(32000, 768)
                   (layer): ModuleList(
                   ...

  File "/home/amiya/workspace/abcd/gector/gector/bert_token_embedder.py", line 147, in forward
    attention_mask=util.combine_initial_dims(input_mask),
                   │    │                    └ tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0')
                   │    └ <function combine_initial_dims at 0x7f174699bbf8>
                   └ <module 'allennlp.nn.util' from '/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/allennlp/nn/util.py'>

  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
             │    │        │        └ {'input_ids': tensor([[ 4145,  7416,    83,  3158,  6490, 24531,   658,    35,    30,    24,
             │    │        │                     948,   191,  4145,   ...
             │    │        └ ()
             │    └ <function XLNetModel.forward at 0x7f1741ff9400>
             └ XLNetModel(
                 (word_embedding): Embedding(32000, 768)
                 (layer): ModuleList(
                   (0): XLNetLayer(
                     (rel_attn): XLNetRela...
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/transformers/modeling_xlnet.py", line 798, in forward
    word_emb_k = self.word_embedding(input_ids)
                 │                   └ tensor([[ 4145],
                 │                             [ 7416],
                 │                             [   83],
                 │                             [ 3158],
                 │                             [ 6490],
                 │                             [24531],
                 │                             [  658],
                 │                           ...
                 └ XLNetModel(
                     (word_embedding): Embedding(32000, 768)
                     (layer): ModuleList(
                       (0): XLNetLayer(
                         (rel_attn): XLNetRela...
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[ 4145],
             │    │                  [ 7416],
             │    │                  [   83],
             │    │                  [ 3158],
             │    │                  [ 6490],
             │    │                  [24531],
             │    │                  [  658],
             │    │               ...
             │    └ <function Embedding.forward at 0x7f17d4b24bf8>
             └ Embedding(32000, 768)
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
    │    │          │    │                   │    └ False
    │    │          │    │                   └ Embedding(32000, 768)
    │    │          │    └ False
    │    │          └ Embedding(32000, 768)
    │    └ 2.0
    └ Embedding(32000, 768)
  File "/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           │     │         │       │      │            │                   └ False
           │     │         │       │      │            └ False
           │     │         │       │      └ -1
           │     │         │       └ tensor([[ 4145],
           │     │         │                 [ 7416],
           │     │         │                 [   83],
           │     │         │                 [ 3158],
           │     │         │                 [ 6490],
           │     │         │                 [24531],
           │     │         │                 [  658],
           │     │         │               ...
           │     │         └ Parameter containing:
           │     │           tensor([[-0.0049,  0.0655, -0.0151,  ..., -0.0458, -0.0061,  0.0346],
           │     │                   [ 0.0395,  0.0205,  0.010...
           │     └ <built-in method embedding of type object at 0x7f17dc678220>
           └ <module 'torch' from '/media/amiya/hdd/miniconda/envs/al/lib/python3.6/site-packages/torch/__init__.py'>

RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_index_select
```
same error I am facing when run it on cpu
