### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by mtorabirad** [grammarly/gector#91]
@skurzhanskyi 
Running an inference with bert, i get this error:

Exception has occurred: KeyError
'@@UNKNOWN@@'
  File "C:\DATA\Projects\PortFolioProjects\NLPCapstone\GectorCode\gector\gector\seq2labels_model.py", line 74, in __init__
    namespace=detect_namespace)
  File "C:\DATA\Projects\PortFolioProjects\NLPCapstone\GectorCode\gector\gector\gec_model.py", line 87, in __init__
    confidence=self.confidence
  File "C:\DATA\Projects\PortFolioProjects\NLPCapstone\GectorCode\gector\predict.py", line 42, in main
    weigths=args.weights)
  File "C:\DATA\Projects\PortFolioProjects\NLPCapstone\GectorCode\gector\predict.py", line 128, in <module>
    main(args)
    
My system is conda python 3.6.12 64 bit Windows

**Comment by skurzhanskyi** [comment]
Can you please specify your command in more detail?

**Comment by mtorabirad** [comment]
Actually, I think this was a Windows issue. I followed the instructions at the end of #36 and it worked.

**Comment by xyiiinexg3** [comment]
Excuse me, i want to know if i can run inference in Windows? If yes, what should i do? 
`Namespace: d_tags
Token: INCORRECT
Traceback (most recent call last):
  File "predict.py", line 131, in <module>
    main(args)
  File "predict.py", line 47, in main
    weigths=args.weights)
  File "D:\xyiiinexg3\1.Workstation\VSCode\gector\gector\gec_model.py", line 66, in __init__
    del_confidence=self.del_conf,
  File "D:\xyiiinexg3\1.Workstation\VSCode\gector\gector\seq2labels_model.py", line 76, in __init__
    namespace=detect_namespace)
  File "D:\Anaconda3\envs\gector\lib\site-packages\allennlp\data\vocabulary.py", line 630, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'`
