### ISSUE TITLE
Error while predicting 

### ISSUE THREAD

**Issue by yeounyi** [grammarly/gector#95]
Hi! Thanks for sharing this amazing model. 
I downloaded pretrained roberta model and am trying to correct some ungrammatical sentences.
I installed all requirements and created a txt input file (inputs.txt). 
But when I run the code below and it throws an error. 
```python3 predict.py --model_path roberta_1_gector.th --input_file inputs.txt --output_file outputs.txt``` 

If I did something wrong, please let me know! 

And if I want to add special tokens to pretrained model, how can I do it?
My sentences contain some special tokens like <name>, <date> and I'm not sure how this pretrained model will handle these tokens. 
Thanks :) 

> 2021-03-05 15:21:01.206637: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-8.0/lib64:/usr/local/cuda/extras/CUPTI/:
2021-03-05 15:21:01.206707: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "predict.py", line 4, in <module>
    from gector.gec_model import GecBERTModel
  File "/home/yeoun/gector/gector/gec_model.py", line 17, in <module>
    from gector.seq2labels_model import Seq2Labels
  File "/home/yeoun/gector/gector/seq2labels_model.py", line 8, in <module>
    from allennlp.models.model import Model
  File "/home/yeoun/.local/lib/python3.6/site-packages/allennlp/models/__init__.py", line 8, in <module>
    from allennlp.models.bert_for_classification import BertForClassification
  File "/home/yeoun/.local/lib/python3.6/site-packages/allennlp/models/bert_for_classification.py", line 11, in <module>
    from allennlp.training.metrics import CategoricalAccuracy
  File "/home/yeoun/.local/lib/python3.6/site-packages/allennlp/training/__init__.py", line 1, in <module>
    from allennlp.training.no_op_trainer import NoOpTrainer
  File "/home/yeoun/.local/lib/python3.6/site-packages/allennlp/training/no_op_trainer.py", line 7, in <module>
    from allennlp.training.trainer import TrainerPieces
  File "/home/yeoun/.local/lib/python3.6/site-packages/allennlp/training/trainer.py", line 29, in <module>
    from allennlp.training.tensorboard_writer import TensorboardWriter
  File "/home/yeoun/.local/lib/python3.6/site-packages/allennlp/training/tensorboard_writer.py", line 5, in <module>
    from tensorboardX import SummaryWriter
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/__init__.py", line 4, in <module>
    from .writer import FileWriter, SummaryWriter
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 24, in <module>
    from .src import event_pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/src/event_pb2.py", line 16, in <module>
    from tensorboardX.src import summary_pb2 as tensorboardX_dot_src_dot_summary__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/src/summary_pb2.py", line 16, in <module>
    from tensorboardX.src import tensor_pb2 as tensorboardX_dot_src_dot_tensor__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/src/tensor_pb2.py", line 16, in <module>
    from tensorboardX.src import resource_handle_pb2 as tensorboardX_dot_src_dot_resource__handle__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/src/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n&tensorboardX/src/resource_handle.proto\x12\x0btensorboard\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB/\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01\xf8\x01\x01\x62\x06proto3')
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/descriptor.py", line 878, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboardX/src/resource_handle.proto":
  tensorboard.ResourceHandleProto.device: "tensorboard.ResourceHandleProto.device" is already defined in file "tensorboard/compat/proto/resource_handle.proto".
  tensorboard.ResourceHandleProto.container: "tensorboard.ResourceHandleProto.container" is already defined in file "tensorboard/compat/proto/resource_handle.proto".
  tensorboard.ResourceHandleProto.name: "tensorboard.ResourceHandleProto.name" is already defined in file "tensorboard/compat/proto/resource_handle.proto".
  tensorboard.ResourceHandleProto.hash_code: "tensorboard.ResourceHandleProto.hash_code" is already defined in file "tensorboard/compat/proto/resource_handle.proto".
  tensorboard.ResourceHandleProto.maybe_type_name: "tensorboard.ResourceHandleProto.maybe_type_name" is already defined in file "tensorboard/compat/proto/resource_handle.proto".
  tensorboard.ResourceHandleProto: "tensorboard.ResourceHandleProto" is already defined in file "tensorboard/compat/proto/resource_handle.proto".

**Comment by yeounyi** [comment]
I solved this by upgrading tensorboardX.
